unit INITHELP;

interface

const

  hcAbout                = 32770;
  hcAutoVal              = 32785;
  hcBetainfo             = 32795;
  hcBoards               = 32778;
  hcBuglist              = 32796;
  hcC                    = 32772;
  hcColor                = 32784;
  hcEvents               = 32781;
  hcfaq                  = 32797;
  hcGetPath              = 32774;
  hcInit                 = 32792;
  hcInstall              = 32775;
  hcInstall2             = 32771;
  hcLaston               = 32788;
  hcmultinode            = 32793;
  hcNetwork              = 32782;
  hcNoContext            = 32768;
  hcNodes                = 32783;
  hcQuit                 = 32769;
  hcRegit1               = 32789;
  hcRegit2               = 32773;
  hcsiteapp              = 32790;
  hcStatus               = 32776;
  hcString               = 32780;
  hcthanks               = 32791;
  hcThisnode             = 32777;
  hcUpgrade              = 32794;
  hcUploads              = 32779;
  hcUser                 = 32786;
  hcZlog                 = 32787;

implementation

end.
